
```{r setup, message=FALSE, warning=FALSE, results='hide'}

####lets see if it is saved
###lets check out again

###changing it again here2

p_needed <-
  c("tidyverse", "ggplot2", "MASS", "optimx", "haven", "foreign", 
    "stargazer", "vcd", "ggridges", "margins", "clarify", "broom", "psych",
    "sjPlot")

packages <- rownames(installed.packages())

p_to_install <- p_needed[!(p_needed %in% packages)]

if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}

sapply(p_needed, require, character.only = TRUE)


stargazer_opt <- ifelse(knitr::is_latex_output(), "latex", "html")

if (stargazer_opt == "html"){
  fargs <- formals(stargazer)
  fargs$notes.append = FALSE
  fargs$notes = c("<sup>&sstarf;</sup>p<0.1; <sup>&sstarf;&sstarf;</sup>p<0.05; <sup>&sstarf;&sstarf;&sstarf;</sup>p<0.01")
  formals(stargazer) <- fargs
}

# only relevant for ggplot2 plotting
# setting a global ggplot theme for the entire document to avoid 
# setting this individually for each plot 
theme_set(theme_classic() + # start with classic theme 
  theme(
    plot.background = element_blank(),# remove all background 
    plot.title.position = "plot", # move the plot title start slightly 
    legend.position = "bottom" # by default, put legend on the bottom
  ))

```


```{r read raw data ESS8}

raw8 <- read_dta("ESS8e02_2/ESS8e02_2.dta")

df8_raw <- raw8

df8 <- raw8[, c("idno", "cntry", "rlgdnm", "rlgblg", "lrscale", "agea", "gndr", 
                "hinctnta", "eisced", "domicil", "rlgatnd", "rlgdgr", "pray", 
                'prtvtbat', 'prtvtcbe', 'prtvtdcz', 'prtvtfee', 'prtvtdfi', 
                'prtvtcfr', 'prtvede1', 'prtvede2', 'prtvtehu', 'prtvtbit', 
                'prtvtfnl', 'prtvtbno', 'prtvtdpl', 'prtvtbse', 'prtvtfch', 
                'prtvtbgb', 'vote', "ppltrst", "pplfair", "imwbcnt", "imsmetn",
                "imdfetn", "impcntr", "imbgeco", "imueclt", "pspwght", "sclmeet")]

df8$pray <-  abs(df8$pray - 8 )
df8$rlgatnd <-  abs(df8$rlgatnd - 8 )
df8$urban <-  abs(df8$domicil - 6 )
df8$female <- df8$gndr - 1

df8$ageasq <- df8$agea^2

df8 <- filter(df8, cntry %in% c('AT', 'BE', 'CZ', 'EE', 'FI', 'FR', 'DE',
                                'HU', 'IT', 'NL', 'NO', 'PL', 'SE', 'CH', 'GB'))

df8 <- filter(df8, vote == 1)

df8 <- filter(df8, eisced != 55)

df8$relg <- ifelse(df8$rlgdnm %in% c(1:4), 1, ifelse(df8$rlgdnm == 6, 2, 
                                             ifelse(df8$rlgdnm %in% c(5,7,8), 3, 0)))


df8 <- df8[, !(colnames(df8) %in% c("rlgdnm", "rlgblg", "gndr", "domicil", "vote"))]

df8_at  <- filter(df8, cntry == "AT", relg == 1)
df8_be  <- filter(df8, cntry == "BE", relg == 1)
df8_cz  <- filter(df8, cntry == "CZ", relg == 1)
df8_ee  <- filter(df8, cntry == "EE", relg == 1)
df8_fi  <- filter(df8, cntry == "FI", relg == 1)
df8_fr  <- filter(df8, cntry == "FR", relg == 1)
df8_de  <- filter(df8, cntry == "DE", relg == 1)
df8_hu  <- filter(df8, cntry == "HU", relg == 1)
df8_it  <- filter(df8, cntry == "IT", relg == 1)
df8_nl  <- filter(df8, cntry == "NL", relg == 1)
df8_no  <- filter(df8, cntry == "NO", relg == 1)
df8_pl  <- filter(df8, cntry == "PL", relg == 1)
df8_se  <- filter(df8, cntry == "SE", relg == 1)
df8_ch  <- filter(df8, cntry == "CH", relg == 1)
df8_gb  <- filter(df8, cntry == "GB", relg == 1)


df8_at$pop  <- ifelse(df8_at$prtvtbat == 3, 1,  
               ifelse(!is.na(df8_at$prtvtbat), 0, NA))

df8_be$pop  <- ifelse(df8_be$prtvtcbe == 7, 1,  
               ifelse(!is.na(df8_be$prtvtcbe), 0, NA))

df8_cz$pop  <- ifelse(df8_cz$prtvtdcz == 7, 1,  
               ifelse(!is.na(df8_cz$prtvtdcz), 0, NA))

df8_ee$pop  <- ifelse(df8_ee$prtvtfee == 6, 1,  
               ifelse(!is.na(df8_ee$prtvtfee), 0, NA))

df8_fi$pop  <- ifelse(df8_fi$prtvtdfi == 4, 1,  
               ifelse(!is.na(df8_fi$prtvtdfi), 0, NA))

df8_fr$pop  <- ifelse(df8_fr$prtvtcfr == 2, 1,  
               ifelse(!is.na(df8_fr$prtvtcfr), 0, NA))

df8_de$pop  <- ifelse(df8_de$prtvede1 == 6, 1,  
               ifelse(!is.na(df8_de$prtvede1), 0, NA))

df8_hu$pop  <- ifelse(df8_hu$prtvtehu %in% c(1,2), 1,  
               ifelse(!is.na(df8_hu$prtvtehu), 0, NA))

df8_it$pop  <- ifelse(df8_it$prtvtbit %in% c(9,10), 1,  
               ifelse(!is.na(df8_it$prtvtbit), 0, NA))

df8_nl$pop  <- ifelse(df8_nl$prtvtfnl == 3, 1,  
               ifelse(!is.na(df8_nl$prtvtfnl), 0, NA))

df8_no$pop  <- ifelse(df8_no$prtvtbno == 8, 1,  
               ifelse(!is.na(df8_no$prtvtbno), 0, NA))

df8_pl$pop  <- ifelse(df8_pl$prtvtdpl %in% c(2,6), 1,  
               ifelse(!is.na(df8_pl$prtvtdpl), 0, NA))

df8_se$pop  <- ifelse(df8_se$prtvtbse == 10, 1,  
               ifelse(!is.na(df8_se$prtvtbse), 0, NA))

df8_ch$pop  <- ifelse(df8_ch$prtvtfch == 1, 1,  
               ifelse(!is.na(df8_ch$prtvtfch), 0, NA))

df8_gb$pop  <- ifelse(df8_gb$prtvtbgb == 7, 1,  
               ifelse(!is.na(df8_gb$prtvtbgb), 0, NA))


df8_pool <- rbind(df8_at, df8_be, df8_cz, df8_ee, df8_fi, df8_fr, df8_de, df8_hu, 
                 df8_it, df8_nl, df8_no, df8_pl, df8_se, df8_ch, df8_gb)

df8_pool <- df8_pool[, !(colnames(df8_pool) %in% c('prtvtbat', 'prtvtcbe', 'prtvtdcz',
                                                    'prtvtfee', 'prtvtdfi', 'prtvtcfr', 'prtvede1', 
                                                    'prtvede2', 'prtvtehu', 'prtvtbit', 'prtvtfnl', 
                                                    'prtvtbno', 'prtvtdpl', 'prtvtbse', 'prtvtfch', 'prtvtbgb'))]



df8_pool$reg4 <- ifelse(df8_pool$cntry %in% c("AT", "BE", "FR", "DE", "NL", "CH", "GB", "IT"), "West",
                       ifelse(df8_pool$cntry %in% c("CZ", "HU", "PL"), "East", "North"))

cntry_names <- c('AT', 'BE', 'CZ', 'EE', 'FI', 'FR', 'DE',
                                'HU', 'IT', 'NL', 'NO', 'PL', 'SE', 'CH', 'GB')


```

```{r ess8 models}

m8_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd    + cntry,
             data = df8_pool, family = "binomial")

m8_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + pray  + cntry,
             data = df8_pool, family = "binomial")

m8_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgdgr + cntry,
             data = df8_pool, family = "binomial")

m8_ch_mr <- as.data.frame(summary(margins(m8_ch, variables = c("rlgatnd"))))
m8_pry_mr <- as.data.frame(summary(margins(m8_pry, variables = c("pray"))))
m8_rlg_mr <- as.data.frame(summary(margins(m8_rlg, variables = c("rlgdgr"))))

res8_rub <- m8_ch_mr

for (i in 1:length(cntry_names)){
  
  
  m_temp  <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + 
                           eisced + urban + rlgatnd    + cntry,
             data = filter(df8_pool, cntry != cntry_names[i]), family = "binomial")
 
m8_temp <- as.data.frame(summary(margins(m_temp, variables = c("rlgatnd"))))
   
res8_rub <- rbind(res8_rub, m8_temp)

 
}

res8_rub$model <- c("all", cntry_names)

res8_rub[2:7] <- round(res8_rub[2:7],4)

m8_trust <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd  +pplfair  + cntry,
             data = df8_pool, family = "binomial")


m8_imm <- lm(imwbcnt ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd  +ppltrst  + cntry,
             data = df8_pool)

m8_trust_dv <- lm(ppltrst ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd  + cntry,
             data = df8_pool)

```



```{r ess10 poplist}

# df10_1 <- read_dta("ESS10/ESS10.dta")
# df10_2 <- read_dta("ESS10/ESS10SC.dta")

df10_1_raw <- df10_1
df10_2_raw <- df10_2

df10_2_raw <- df10_2_raw[, c('idno', 'cntry', 'psppsgva', 'psppipla', 'trstplt', 
'trstprt', 'vote', 'prtvtcat', 'prtvtccy', 'prtvfde1', 'prtvfde2', 'prtvtalv', 
'prtvtepl', 'prtvtars', 'prtvtfes', 'prtvtdse', 'lrscale', 'sclmeet', 'sclact',
'rlgdnm', 'rlgdgr', 'rlgatnd', 'pray', 'gndr', 'agea', 'domicil', 
'eisced', 'hinctnta', 'secgrdec', 'scidecpb', 'gvconc19', 'mode',"ppltrst", "pplfair",
"imwbcnt", "imsmetn","imdfetn", "impcntr", "imbgeco", "imueclt", "pspwght", "scrlgblg")]

df10_2_raw[, c('prtvtebe', 'prtvtebg', 'prtvthch', 'prtvtbhr', 'prtvtecz', 
               'prtvthee', 'prtvtefi', 'prtvtefr', 'prtvtdgr', 'prtvtghu', 
               'prtvtdis', 'prtvtdie', 'prtvtdit', 'prtvclt1', 'prtvclt2', 
               'prtvclt3', 'prtvtame', 'prtvthnl', 'prtvtmk', 'prtvtbno', 
               'prtvtdpt', 'prtvtfsi', 'prtvtesk', 'prtvtdgb')] <- NA

df10_2_raw$rlgblg <- ifelse(df10_2_raw$scrlgblg ==1, 1, ifelse(!is.na(df10_2_raw$scrlgblg), 2, NA))

df10_2_raw <- df10_2_raw[, colnames(df10_2_raw) != "scrlgblg"]


df10_1_raw <- df10_1_raw[, c('idno', 'cntry', 'psppsgva', 'psppipla', 'trstplt', 
               'trstprt', 'vote', 'prtvtebe', 'prtvtebg', 'prtvthch', 'prtvtbhr', 'prtvtecz', 
               'prtvthee', 'prtvtefi', 'prtvtefr', 'prtvtdgr', 'prtvtghu', 
               'prtvtdis', 'prtvtdie', 'prtvtdit', 'prtvclt1', 'prtvclt2', 
               'prtvclt3', 'prtvtame', 'prtvthnl', 'prtvtmk', 'prtvtbno', 
               'prtvtdpt', 'prtvtfsi', 'prtvtesk', 'prtvtdgb', 'lrscale', 'sclmeet', 
               'sclact', 'rlgdnm', 'rlgdgr', 'rlgatnd', 'pray', 'gndr', 'agea', 'domicil', 
               'eisced', 'hinctnta', 'secgrdec', 'scidecpb', 'gvconc19', 'mode',
               "ppltrst", "pplfair", "imwbcnt", "imsmetn","imdfetn", "impcntr", 
               "imbgeco", "imueclt", "pspwght", "rlgblg")]

df10_1_raw[, c('prtvtcat', 'prtvtccy', 'prtvfde1', 'prtvfde2', 'prtvtalv', 
'prtvtepl', 'prtvtars', 'prtvtfes', 'prtvtdse')] <- NA

df10_raw <- rbind(df10_1_raw,df10_2_raw)

rm(df10_1_raw, df10_2_raw)

df10 <- df10_raw

df10$match <- paste(df10$idno, df10$cntry, df10$mode, sep = "-")

df10$pray <-  abs(df10$pray - 8 )
df10$rlgatnd <-  abs(df10$rlgatnd - 8 )
df10$urban <-  abs(df10$domicil - 6 )
df10$female <- df10$gndr - 1

df10$ageasq <- df10$agea^2

df10 <- filter(df10, vote == 1)

df10 <- filter(df10, eisced != 55)

df10$relg <- ifelse(df10$rlgdnm %in% c(1:4), 1, ifelse(df10$rlgdnm == 6, 2, 
                                             ifelse(df10$rlgdnm %in% c(5,7,8), 3, 0)))

df10$popr <- NA
df10[df10$cntry == "FI",]$popr  <- ifelse(df10[df10$cntry == "FI",]$prtvtefi == 5, 1,  
               ifelse(!is.na(df10[df10$cntry == "FI",]$prtvtefi), 0, NA))

df10[df10$cntry == "DE",]$popr  <- ifelse(df10[df10$cntry == "DE",]$prtvfde1 == 6, 1,  
               ifelse(!is.na(df10[df10$cntry == "DE",]$prtvfde1), 0, NA))

df10[df10$cntry == "PL",]$popr  <- ifelse(df10[df10$cntry == "PL",]$prtvtepl == 5, 1,  
               ifelse(!is.na(df10[df10$cntry == "PL",]$prtvtepl), 0, NA))

df10[df10$cntry == "IT",]$popr  <- ifelse(df10[df10$cntry == "IT",]$prtvtdit %in% c(3,5), 1,  
               ifelse(!is.na(df10[df10$cntry == "IT",]$prtvtdit), 0, NA))

df10[df10$cntry == "AT",]$popr  <- ifelse(df10[df10$cntry == "AT",]$prtvtcat %in% c(3), 1,  
               ifelse(!is.na(df10[df10$cntry == "AT",]$prtvtcat), 0, NA))


df10[df10$cntry == "BE",]$popr  <- ifelse(df10[df10$cntry == "BE",]$prtvtebe %in% c(3,5), 1,  
               ifelse(!is.na(df10[df10$cntry == "BE",]$prtvtebe), 0, NA))


df10[df10$cntry == "CZ",]$popr  <- ifelse(df10[df10$cntry == "CZ",]$prtvtecz %in% c(8), 1,  
               ifelse(!is.na(df10[df10$cntry == "CZ",]$prtvtecz), 0, NA))


df10[df10$cntry == "EE",]$popr  <- ifelse(df10[df10$cntry == "EE",]$prtvthee %in% c(2,6), 1,  
               ifelse(!is.na(df10[df10$cntry == "EE",]$prtvthee), 0, NA))

df10[df10$cntry == "FR",]$popr  <- ifelse(df10[df10$cntry == "FR",]$prtvtefr %in% c(11,10), 1,  
               ifelse(!is.na(df10[df10$cntry == "FR",]$prtvtefr), 0, NA))

df10[df10$cntry == "HU",]$popr  <- ifelse(df10[df10$cntry == "HU",]$prtvtghu %in% c(3,4), 1,  
               ifelse(!is.na(df10[df10$cntry == "HU",]$prtvtghu), 0, NA))

df10[df10$cntry == "NL",]$popr  <- ifelse(df10[df10$cntry == "NL",]$prtvthnl %in% c(13,3,16,17), 1,  
               ifelse(!is.na(df10[df10$cntry == "NL",]$prtvthnl), 0, NA))

df10[df10$cntry == "NO",]$popr  <- ifelse(df10[df10$cntry == "NO",]$prtvtbno %in% c(8), 1,  
               ifelse(!is.na(df10[df10$cntry == "NO",]$prtvtbno), 0, NA))

df10[df10$cntry == "SE",]$popr  <- ifelse(df10[df10$cntry == "SE",]$prtvtdse %in% c(7), 1,  
               ifelse(!is.na(df10[df10$cntry == "SE",]$prtvtdse), 0, NA))

df10[df10$cntry == "CH",]$popr  <- ifelse(df10[df10$cntry == "CH",]$prtvthch %in% c(1,10,15), 1,  
               ifelse(!is.na(df10[df10$cntry == "CH",]$prtvthch), 0, NA))


df10[df10$cntry == "GB",]$popr  <- ifelse(df10[df10$cntry == "GB",]$prtvtdgb %in% c(7,8), 1,  
               ifelse(!is.na(df10[df10$cntry == "GB",]$prtvtdgb), 0, NA))



df10_pool <- filter(df10, cntry %in% cntry_names)


df10_pool <- filter(df10_pool, relg == 1)



df10_pool <- df10_pool[, c("popr", "lrscale", "agea", "ageasq" ,"female", "hinctnta", 
                             "eisced", "urban", "rlgatnd", "pray", "rlgdgr", "cntry","ppltrst", "pplfair",
                           "imwbcnt", "imsmetn","imdfetn", "impcntr", "imbgeco", "imueclt", "pspwght", "match")]




m10_pool <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd +cntry ,
             data = df10_pool, family = "binomial", weights = pspwght )


svg("robust.svg")

 plot(
    density(res8_rub$AME),
    xlim = c(-0.02,0),
    main = "",
    xlab = "AME of Church Attendance on Probability PRR Vote",
    ylab = "Density",
    yaxs = "i",
    xaxs = "i",
    lwd = 1.5,
    ylim = c(0,600)
    )
 
 lines(density(res10_rub$AME),
       lwd = 1.5,
       col = "grey")
 
 legend("topleft", 
        title = "ESS Wave",
       legend = c("2021", "2016"), 
       lwd = c(1.5, 1.5), 
       col = c("black", "grey")
       )
 
 
 dev.off()



```


```{r simulations}

corona <- read.csv2("corona.csv")

corona <- group_by(corona, cntry) %>% summarise(max_corona = max(stringent), avg_corona = mean(stringent))

df10_cor <- left_join(df10_pool, corona, by = "cntry")


m10_cor <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd + rlgatnd:max_corona + cntry ,
             data = df10_cor, family = "binomial", weights = pspwght )

m10_cor2 <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd + rlgatnd:avg_corona + cntry ,
             data = df10_cor, family = "binomial", weights = pspwght )


c_m1 <- sim(fit = m10_cor, n= 1000, vcov = vcov(m10_cor), coefs= coef(m10_cor))
# sim_m1 <- sim_adrf(c_m1, var = "rlgatnd",
#                    contrast = "adrf", at = 1:7, verbose = F)

sim_m1 <- sim_setx(c_m1, x = list(rlgatnd = 1:7, max_corona = c(70,94)), verbose = F)

sim_plot <- as.data.frame(sim_m1)

sim_q <- apply(sim_plot,2,quantile, c(0.025,0.975,0.5))



svg("simulation.svg")

plot(
  c(1:7), sim_q[3,1:7],
  type = "n", 
  las = 1,
  lwd = 2, 
  ylim = c(0, 0.08), 
  yaxs = "i", 
  xaxs = "i", 
  xlab = "Church Attendance", 
  ylab = "Predicted Probability"
  )

grid()

lines(c(1:7), sim_q[3,1:7], bty = "o")

polygon(
  x = c(rev(c(1:7)), c(1:7)),
  y = c(rev(sim_q[2,1:7]), sim_q[1,1:7]),
  col = adjustcolor("grey60", alpha.f = 0.4),
  border = NA
)


lines(c(1:7), sim_q[3,8:14], lwd = 2, lty = 2)
polygon(
  x = c(rev(c(1:7)), c(1:7)),
  y = c(rev(sim_q[2,8:14]), sim_q[1,8:14]),
  col = adjustcolor("grey60", alpha.f = 0.4),
  border = NA
)

legend("topleft", 
       legend = c("Low Restrictions", "High Restrictions", "95% CI"), 
       lwd = c(2, 2, 10), 
       col = c("black", "black", adjustcolor("grey60", alpha.f = 0.4)), 
       lty = c(1, 2, 1), 
       bty = "n"
       )

dev.off()



# 
# gini_den <- density(na.omit(df1$gini))
# 
# y1 <- apply(sim_m1, 2, quantile, c(0.5,0.975,0.025) )
# 
# svg("plot1.svg")
# 
# plot(c(20,70), c(0,3.25), type = "n" , xaxs = "i", yaxs = "i",
#      ylab = "Trust in Promises from Politicians", xlab ="Gini Index ")
# 
# abline(h = c(1,2,3), lty = 2, col = "darkgrey")
# 
# polygon(x = c(c(25,35,45,55,65), rev(c(25,35,45,55,65))),
#         y = c(y1[2,], rev(y1[3,])),
#         col = "lightgrey",
#         border = F)
# 
# lines(c(25,35,45,55,65), y1[1,], lwd = 2, type = "l")
# 
# 
# 
# lines(gini_den$x, gini_den$y*10)
# 
# dev.off()
# 
# 
# 
# m1a <- polr(as.factor(promise) ~ . -edu2 -WEIGHT -year -c_yr -pcgdp ,
#             data = na.omit(df1),
#           Hess = TRUE,
#           method = "logistic")

```

```{r models 10, warning = F}

m10_ch <- glm(popr ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd    + cntry,
             data = df10_pool, family = "binomial", weights = pspwght )

m10_pry <- glm(popr ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + pray  + cntry,
             data = df10_pool, family = "binomial", weights = pspwght )

m10_rlg <- glm(popr ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgdgr + cntry,
             data = df10_pool, family = "binomial", weights = pspwght )

m10_ch_mr <- as.data.frame(summary(margins(m10_ch, variables = c("rlgatnd"))))
m10_pry_mr <- as.data.frame(summary(margins(m10_pry, variables = c("pray"))))
m10_rlg_mr <- as.data.frame(summary(margins(m10_rlg, variables = c("rlgdgr"))))

res10_rub <- m10_ch_mr

for (i in 1:length(cntry_names)){
  
  
  m_temp  <- glm(popr ~ lrscale + agea + ageasq + female + hinctnta + 
                           eisced + urban + rlgatnd    + cntry,
             data = filter(df10_pool, cntry != cntry_names[i]), family = "binomial", weights = pspwght )
 
m10_temp <- as.data.frame(summary(margins(m_temp, variables = c("rlgatnd"))))
   
res10_rub <- rbind(res10_rub, m10_temp)

 
}

res10_rub$model <- c("all", cntry_names)

res10_rub[2:7] <- round(res10_rub[2:7],4)


m10_imm <- lm(impcntr ~ lrscale + agea + ageasq + female + hinctnta + 
                eisced + urban + rlgatnd  +ppltrst  + cntry,
               data = df10_pool, weights = pspwght )

m10_trust_dv <- lm(ppltrst ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd  + cntry,
             data = df10_pool, weights = pspwght )


####margins for every country

res10_single <- m10_ch_mr

for (i in 1:length(cntry_names)){
  
  
  m_temp  <- glm(popr ~ lrscale + agea + ageasq + female + hinctnta + 
                           eisced + urban + rlgatnd,
             data = filter(df10_pool, cntry == cntry_names[i]), 
             family = "binomial", weights = pspwght)
 
m10_temp <- as.data.frame(summary(margins(m_temp, variables = c("rlgatnd"))))
   
res10_single <- rbind(res10_single, m10_temp)

}

res10_single$model <- c("all", cntry_names)

res10_single[2:7] <- round(res10_single[2:7],4)



###for model 8
res8_single <- m8_ch_mr

for (i in 1:length(cntry_names)){
  
  
  m_temp  <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + 
                           eisced + urban + rlgatnd,
             data = filter(df8_pool, cntry == cntry_names[i]), 
             family = "binomial", weights = pspwght)
 
m8_temp <- as.data.frame(summary(margins(m_temp, variables = c("rlgatnd"))))
   
res8_single <- rbind(res8_single, m8_temp)

}

res8_single$model <- c("all", cntry_names)

res8_single[2:7] <- round(res8_single[2:7],4)


```


```{r CRON2W2e01 all}

df_cron_raw <-  read_dta("ESS10/CRON2W2e01/CRON2W2e01.dta")

df_cron <- df_cron_raw[, c("idno","cntry", "mode", "w2q69")]

df_cron$match <- paste(df_cron$idno, df_cron$cntry, df_cron$mode, sep = "-")

df_cron_all <- inner_join(df_cron, df10, by = "match", suffix = c("", ""))


df_cron_all$fund <- ifelse(df_cron_all$w2q69 %in% c(2,4), 0, ifelse(df_cron_all$w2q69 %in% c(1,3), 1, NA))

df_cron_all <- df_cron_all[, c("popr", "lrscale", "agea", "ageasq" ,"female", "hinctnta", 
                             "eisced", "urban", "rlgatnd", "pray", "rlgdgr", "fund", "cntry", "rlgblg","pspwght", "relg")]

m_cron_all2 <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd + fund +  rlgblg + cntry,
             data = df_cron_all, family = "binomial")

m_cron_all <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd + fund +  rlgblg + cntry,
             data = df_cron_all, family = "binomial", weights = pspwght)

m_cron_all3 <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd   + cntry,
             data = filter(df_cron_all, relg == 1), family = "binomial", weights = pspwght)

m10_rob <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd   + cntry, data = filter(df10_pool, cntry %in% unique(df_cron_all$cntry)), family = "binomial", weights = pspwght)


c_fund <- sim(fit = m_cron_all, n= 1000, vcov = vcov(m_cron_all), coefs= coef(m_cron_all))
sim_fund <- as.data.frame(sim_ame(c_fund, var = "fund", verbose = F))

#quantile((sim_fund[[1]]-sim_fund[[2]]), 0.5)

sim_fund2 <- sim_adrf(c_fund, var = "rlgatnd", contrast = "adrf", at = 1:7, verbose = F)


```




```{r CRON2W2e01 all}

df_cron_1_raw <-  read_dta("ESS10/CRON2W2e01/CRON2W2e01.dta")

df_cron_1 <- df_cron_1_raw[, c("idno","cntry", "mode", "w2q69")]

df_cron_1$match <- paste(df_cron_1$idno, df_cron_1$cntry, df_cron_1$mode, sep = "-")

df_cron_1_all <- inner_join(df_cron_1, df10, by = "match", suffix = c("", ""))


df_cron_1_all$fund <- ifelse(df_cron_1_all$w2q69 %in% c(2,4), 0, ifelse(df_cron_1_all$w2q69 %in% c(1,3), 1, NA))


df_cron_1_all$fund2 <- ifelse(df_cron_1_all$w2q69 %in% c(2,4), "non-fund", ifelse(df_cron_1_all$w2q69 == 1 , "ath_fund", ifelse(df_cron_1_all$w2q69 == 3 , "rel_fund",NA)))


df_cron_r <-  read_dta("ESS10/CRON2W4e01.dta")

df_cron <- df_cron_r[, c("idno","cntry", "mode", "w4q13", 
                           "w4q32", "w4q33", "w4q34", "w4q35", "w4q36", 
                           "w4q37",  "w4q38", "w4q39", "w4q40",
                          "w4q41",  "w4q42", "w4q43", "w4q44",  "w4q45", "w4q46")]

colnames(df_cron)[c(4:19)] <- c("hr", "pop1", "pop2", "pop3", "pop4", "pop5",
                                 "pop6", "pop7", "pop8", "pop9",
                                "tec1", "tec2", "tec3", "tec4", "tec5", "tec6")

df_cron$match <- paste(df_cron$idno, df_cron$cntry, df_cron$mode, sep = "-")

df <- inner_join(df_cron, df_cron_1_all, by = "match", suffix = c("", ""))

df$tec3 <- abs(df$tec3 - 10)
df$tec4 <- abs(df$tec4 - 10)
df$tec5 <- abs(df$tec5 - 10)
df$pop2 <- abs(df$pop2 - 10)
df$pop7 <- abs(df$pop7 - 6)
df$pop9 <- abs(df$pop9 - 6)
# df$con1 <- abs(df$con1 - 6)
# df$con2 <- abs(df$con2 - 6)
# df$con3 <- abs(df$con3 - 6)
# df$freehms <- abs(df$freehms - 6)
# df$rwa <- (df$loylead + df$lrnobed)/2
# df$hmsacld <- abs(df$hmsacld - 6)


npop <- c( "pop1", "pop2", "pop4", "pop5", "pop6")

pca_pop <- principal(df[npop],1, rotate = "varimax")

alpha_pop <- alpha(df[npop])


ntec <- c("tec1", "tec2", "tec3", "tec4", "tec5")

pca_tec <- principal(df[ntec],1, rotate = "varimax")

alpha_tec <- alpha(df[ntec], check.keys  = T)


df$pop <- as.numeric(pca_pop$scores)

df$pop <- df$pop - min(df$pop, na.rm =T)

tec_scores <- as.data.frame(pca_tec$scores)

df$tec <- tec_scores[[1]]

df$tec <- as.numeric(df$tec - min(df$tec, na.rm =T))

df$tec <- ifelse(df$tec < 1, NA, df$tec)

df$tec <- as.numeric(df$tec - min(df$tec, na.rm =T))

m_pop <- lm(pop  ~ fund2   + lrscale  + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd +rlgblg    + cntry, data = df)

m_tec <- lm(tec  ~ fund2   + lrscale  + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd +rlgblg    + cntry, data = df)



m_popr <- glm(popr ~ fund2   + lrscale  + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd +rlgblg    + cntry, data = filter(df, cntry != "GB"), family = "binomial")


df_cron_1_all <- df_cron_1_all[, c("popr", "lrscale", "agea", "ageasq" ,"female", "hinctnta", 
                             "eisced", "urban", "rlgatnd", "pray", "rlgdgr", "fund", "cntry", "rlgblg","pspwght", "relg")]

m_cron_1_all2 <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd + fund +  rlgblg + cntry,
             data = df_cron_1_all, family = "binomial")

m_cron_1_all <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd + fund +  rlgblg + cntry,
             data = df_cron_1_all, family = "binomial", weights = pspwght)

m_cron_1_all3 <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd   + cntry,
             data = filter(df_cron_1_all, relg == 1), family = "binomial", weights = pspwght)

m10_rob <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd   + cntry, data = filter(df10_pool, cntry %in% unique(df_cron_1_all$cntry)), family = "binomial", weights = pspwght)


c_fund <- sim(fit = m_cron_1_all, n= 1000, vcov = vcov(m_cron_1_all), coefs= coef(m_cron_1_all))
sim_fund <- as.data.frame(sim_ame(c_fund, var = "fund", verbose = F))

#quantile((sim_fund[[1]]-sim_fund[[2]]), 0.5)

sim_fund2 <- sim_adrf(c_fund, var = "rlgatnd", contrast = "adrf", at = 1:7, verbose = F)


```



```{r with non-religious}

###ESS

df8_2 <- raw8[, c("idno", "cntry", "rlgdnm", "rlgblg", "lrscale", "agea", "gndr", 
                "hinctnta", "eisced", "domicil", "rlgatnd", "rlgdgr", "pray", 
                'prtvtbat', 'prtvtcbe', 'prtvtdcz', 'prtvtfee', 'prtvtdfi', 
                'prtvtcfr', 'prtvede1', 'prtvede2', 'prtvtehu', 'prtvtbit', 
                'prtvtfnl', 'prtvtbno', 'prtvtdpl', 'prtvtbse', 'prtvtfch', 
                'prtvtbgb', 'vote', "ppltrst", "pplfair", "imwbcnt", "imsmetn",
                "imdfetn", "impcntr", "imbgeco", "imueclt", "pspwght")]

df8_2$pray <-  abs(df8_2$pray - 8 )
df8_2$rlgatnd <-  abs(df8_2$rlgatnd - 8 )
df8_2$urban <-  abs(df8_2$domicil - 6 )
df8_2$female <- df8_2$gndr - 1

df8_2$ageasq <- df8_2$agea^2

df8_2 <- filter(df8_2, cntry %in% c('AT', 'BE', 'CZ', 'EE', 'FI', 'FR', 'DE',
                                'HU', 'IT', 'NL', 'NO', 'PL', 'SE', 'CH', 'GB'))

df8_2 <- filter(df8_2, vote == 1)

df8_2 <- filter(df8_2, eisced != 55)

df8_2$relg <- ifelse(df8_2$rlgdnm %in% c(1:4), 1, ifelse(df8_2$rlgdnm == 6, 2, 
                                             ifelse(df8_2$rlgdnm %in% c(5,7,8), 3, 0)))


df8_2 <- df8_2[, !(colnames(df8_2) %in% c("rlgdnm", "gndr", "domicil", "vote"))]

df8_2_at  <- filter(df8_2, cntry == "AT")
df8_2_be  <- filter(df8_2, cntry == "BE")
df8_2_cz  <- filter(df8_2, cntry == "CZ")
df8_2_ee  <- filter(df8_2, cntry == "EE")
df8_2_fi  <- filter(df8_2, cntry == "FI")
df8_2_fr  <- filter(df8_2, cntry == "FR")
df8_2_de  <- filter(df8_2, cntry == "DE")
df8_2_hu  <- filter(df8_2, cntry == "HU")
df8_2_it  <- filter(df8_2, cntry == "IT")
df8_2_nl  <- filter(df8_2, cntry == "NL")
df8_2_no  <- filter(df8_2, cntry == "NO")
df8_2_pl  <- filter(df8_2, cntry == "PL")
df8_2_se  <- filter(df8_2, cntry == "SE")
df8_2_ch  <- filter(df8_2, cntry == "CH")
df8_2_gb  <- filter(df8_2, cntry == "GB")


df8_2_at$pop  <- ifelse(df8_2_at$prtvtbat == 3, 1,  
               ifelse(!is.na(df8_2_at$prtvtbat), 0, NA))

df8_2_be$pop  <- ifelse(df8_2_be$prtvtcbe == 7, 1,  
               ifelse(!is.na(df8_2_be$prtvtcbe), 0, NA))

df8_2_cz$pop  <- ifelse(df8_2_cz$prtvtdcz == 7, 1,  
               ifelse(!is.na(df8_2_cz$prtvtdcz), 0, NA))

df8_2_ee$pop  <- ifelse(df8_2_ee$prtvtfee == 6, 1,  
               ifelse(!is.na(df8_2_ee$prtvtfee), 0, NA))

df8_2_fi$pop  <- ifelse(df8_2_fi$prtvtdfi == 4, 1,  
               ifelse(!is.na(df8_2_fi$prtvtdfi), 0, NA))

df8_2_fr$pop  <- ifelse(df8_2_fr$prtvtcfr == 2, 1,  
               ifelse(!is.na(df8_2_fr$prtvtcfr), 0, NA))

df8_2_de$pop  <- ifelse(df8_2_de$prtvede1 == 6, 1,  
               ifelse(!is.na(df8_2_de$prtvede1), 0, NA))

df8_2_hu$pop  <- ifelse(df8_2_hu$prtvtehu %in% c(1,2), 1,  
               ifelse(!is.na(df8_2_hu$prtvtehu), 0, NA))

df8_2_it$pop  <- ifelse(df8_2_it$prtvtbit %in% c(9,10), 1,  
               ifelse(!is.na(df8_2_it$prtvtbit), 0, NA))

df8_2_nl$pop  <- ifelse(df8_2_nl$prtvtfnl == 3, 1,  
               ifelse(!is.na(df8_2_nl$prtvtfnl), 0, NA))

df8_2_no$pop  <- ifelse(df8_2_no$prtvtbno == 8, 1,  
               ifelse(!is.na(df8_2_no$prtvtbno), 0, NA))

df8_2_pl$pop  <- ifelse(df8_2_pl$prtvtdpl %in% c(2,6), 1,  
               ifelse(!is.na(df8_2_pl$prtvtdpl), 0, NA))

df8_2_se$pop  <- ifelse(df8_2_se$prtvtbse == 10, 1,  
               ifelse(!is.na(df8_2_se$prtvtbse), 0, NA))

df8_2_ch$pop  <- ifelse(df8_2_ch$prtvtfch == 1, 1,  
               ifelse(!is.na(df8_2_ch$prtvtfch), 0, NA))

df8_2_gb$pop  <- ifelse(df8_2_gb$prtvtbgb == 7, 1,  
               ifelse(!is.na(df8_2_gb$prtvtbgb), 0, NA))


df8_2_pool <- rbind(df8_2_at, df8_2_be, df8_2_cz, df8_2_ee, df8_2_fi, df8_2_fr, df8_2_de, df8_2_hu, 
                 df8_2_it, df8_2_nl, df8_2_no, df8_2_pl, df8_2_se, df8_2_ch, df8_2_gb)

df8_2_pool <- df8_2_pool[, !(colnames(df8_2_pool) %in% c('prtvtbat', 'prtvtcbe', 'prtvtdcz',
                                                    'prtvtfee', 'prtvtdfi', 'prtvtcfr', 'prtvede1', 
                                                    'prtvede2', 'prtvtehu', 'prtvtbit', 'prtvtfnl', 
                                                    'prtvtbno', 'prtvtdpl', 'prtvtbse', 'prtvtfch', 'prtvtbgb'))]

df8_2_pool$rlgblg <- abs(df8_2_pool$rlgblg -2)

m8_2 <- glm(pop ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd +  rlgblg + cntry,
             data = df8_2_pool, family = "binomial")

m8_2_int <- glm(pop ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd*rlgblg + cntry,
             data = df8_2_pool, family = "binomial")




####ESs10

df10_b <- filter(df10, cntry %in% cntry_names)

df10_b$rlgblg <- abs(df10_b$rlgblg -2)


m10_b <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd + rlgblg + cntry ,
             data = df10_b, family = "binomial", weights = pspwght )


```


```{r immigration, warning = F}

immigration <- c("imsmetn", "imdfetn", "impcntr", "imbgeco", "imueclt","imwbcnt")

temp <- tidy(m10_2, conf.int = T)
res_imm <-as.data.frame(temp[1,]) 


variables <- c("rlgatnd", "lrscale", "agea", "ageasq", "female", "hinctnta", "eisced", "urban",  "cntry")



for (i in 1:length(immigration)){
  
dv <- immigration[i]

f <- as.formula(paste(dv, paste(variables, collapse = " + "),sep = " ~ "))

  
 m_temp  <- lm(f, data = df8_pool, weights = pspwght)
  
temp1 <- tidy(m_temp, conf.int = T)[2,]
  
m_temp  <- lm(f, data = df10_pool, weights = pspwght)
 
temp2 <- tidy(m_temp, conf.int = T)[2,]
   
res_imm <- rbind(res_imm, temp1,temp2)

res_imm$term[c(2*i, 2*i+1)] <- immigration[i]
 
}

res_imm <- res_imm[-1,]

res_imm[2:7] <- round(res_imm[2:7], 3)

res_imm <- res_imm[c(1,2,6,7,3,4,5)]

res_abs_imm <- apply(res_imm[,c(2:4)], 2, abs)

y1 <- c(1.5,4.5,7.5,10.5,13.5,16.5)
  
labs <- c("Diff race/ethnicity",
         "Same race/ethnicity",
         "From outside Europe",
         "Good for economy",
         "Enrich culture",
         "Life in country better")

svg("immigration.svg")

#par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
par(xpd=T, mar = c(5,8,2,2) +0.1)


plot (c(-0.05,0.2), 
      c(0,18), 
      type = "n",
      xlim = c(-0.05,0.2),
      ylab = "",
      ylim =  c(0,18),
      yaxt = "n",
      xlab = "Coefficient of Church Attendance",
      yaxs="i",
      xaxs="i" )



#rect(0.12,18+0.3, 0.16, 18+2.5)


par(xpd=F)

abline(h = c(1,2,4,5,7,8,10,11,13,14,16,17), lty = 2 , col = "lightgrey")


for (i in 1:6){
  lines(res_abs_imm[2*i-1,2:3],c(3*i-2,3*i-2))
  lines(res_abs_imm[2*i,2:3],c(3*i-1,3*i-1))
}

points(res_abs_imm[,1], 
       c(1,2,4,5,7,8,10,11,13,14,16,17),
       pch = c(19,17,19,17,19,17,19,17,19,17,19,17),
       col = "black")
 

axis(side = 2, at = y1, labels = labs, cex.axis = 0.8, las = 1)

abline(v = 0, )

legend(0.14, 3,
       c("  2021  ", "  2016  "), 
       pch = c(17,19), 
       col = c("black") ,
       pt.bg = c("black") ,
       title = "  ESS Wave  ",
      # bty = "n",
       ncol = 1,
       cex = 1,
       pt.cex = 1)

par(xpd=T)
# text(-0.1, 1.5, "Math")
# text(-0.1, 4.5, "Reading")
# text(-0.1, 7.5, "Math")
# text(-0.1, 10.5, "Reading")
# text(-0.1, 13.5, "Math")
# text(-0.1, 16.5, "Reading")

dev.off()



```


```{r islam}

df10_mc <- filter(df10, cntry %in% cntry_names)


df10_mc <- filter(df10_mc, relg %in% c(1,2))

df10_mc$mus <- df10_mc$relg - 1



df10_mc <- df10_mc[, c("popr", "lrscale", "agea", "ageasq" ,"female", "hinctnta", 
                             "eisced", "urban", "rlgatnd", "pray", "rlgdgr", "cntry","ppltrst", "pplfair",
                           "imwbcnt", "imsmetn","imdfetn", "impcntr", "imbgeco", "imueclt", "pspwght", "match", "mus")]




m10_mc <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd +mus +cntry ,
             data = df10_mc, family = "binomial", weights = pspwght )


m10_mc_int <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd*mus +cntry ,   data = df10_mc, family = "binomial", weights = pspwght )



```



```{r descriptive stats}

sum_stat_10 <- df10_b %>%  dplyr::select(pspwght, rlgblg, rlgatnd, cntry)  %>% 
         na.omit() %>% group_by(cntry) %>% 
           summarise(religious = round(sum(pspwght * (rlgblg == 1))/sum(pspwght)*100,0),
                        attend = round(sum(pspwght * rlgatnd/sum(pspwght) ),1))


sum_stat_8 <- df8_2_pool %>%  dplyr::select(pspwght, rlgblg, rlgatnd, cntry)  %>% 
         na.omit() %>% group_by(cntry) %>% 
           summarise(religious = round(sum(pspwght * (rlgblg == 1))/sum(pspwght)*100,0),
                        attend = round(sum(pspwght * rlgatnd/sum(pspwght) ),1))


sum_stat <- cbind(sum_stat_8,sum_stat_10)

write.csv2(sum_stat, "summary_stat.csv", row.names = F)




```



```{r model 1, warning = F, results =  "asis", message = "F"}


fargs <- formals(stargazer)
  fargs$notes.append = FALSE
  fargs$notes = c("\\textit{Note:} $^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01")
  formals(stargazer) <- fargs


m8a <- glm(pop ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd +  rlgblg +    cntry, data = df8_2_pool, family = "binomial") 

m8b <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd    + cntry,
             data = df8_pool, family = "binomial", weights = pspwght )

m8c <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgdgr + cntry,
             data = df8_pool, family = "binomial", weights = pspwght )

m8d<- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + pray  + cntry,
             data = df8_pool, family = "binomial", weights = pspwght )

m8e<- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd + ppltrst + sclmeet  + cntry,
             data = df8_pool, family = "binomial", weights = pspwght )


  
stargazer(list(m8a,m8b,m8c,m8d,m8e),
          type = stargazer_opt,
          out = "m8.tex",
         covariate.labels = c( "Church Attendance", "Believer", 
         "self-reported Religioisty", "Private Prayer", "Social Trust", "Social Contacts"),   
         keep =  c("rlgatnd", "rlgblg", "rlgdgr", "pray", "ppltrst" , "sclmeet"),
         dep.var.labels = c("Probability of Voting for PRR"),           
         model.names = FALSE,
         title = "Probability of Voting for PRR Parties from ESS wave 2016-2017",
         add.lines=list(c("Demographic Controls", "Yes", "Yes", "Yes", "Yes", "Yes"), c("Income and Education", "Yes", "Yes", "Yes", "Yes", "Yes"), c("Left-Right Scale", "Yes", "Yes", "Yes", "Yes", "Yes"),c("Urban Settlement", "Yes", "Yes", "Yes", "Yes", "Yes"),c("Country FE", "Yes", "Yes", "Yes", "Yes", "Yes")),
          intercept.top = F,
          style = "apsr",
          table.placement = "H"
          )


```


```{r model 2, warning = F, results =  "asis", message = "F"}


fargs <- formals(stargazer)
  fargs$notes.append = FALSE
  fargs$notes = c("\\textit{Note:} $^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01")
  formals(stargazer) <- fargs


m10a <- glm(popr ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd + cntry,
             data = df10_pool, family = "binomial", weights = pspwght )

m10b <- glm(popr ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd + rlgatnd:max_corona + cntry,
             data = df10_cor, family = "binomial", weights = pspwght )



  
stargazer(list(m8b,m10a,m10b),
          type = stargazer_opt,
          out = "m10.tex",
         covariate.labels = c( "Church Attendance", "Church Attend. x COVID Restrictions"),   
         keep =  c("rlgatnd", "rlgatnd:max_corona"),
         dep.var.labels = c("Probability of Voting for PRR"),           
         model.names = FALSE,
          column.labels = c("2016", "2021", "2021"),
         title = "Probability of Voting for PRR Parties from ESS wave 2016-2017",
         add.lines=list(c("Demographic Controls", "Yes", "Yes", "Yes"), c("Income and Education", "Yes", "Yes", "Yes"), c("Left-Right Scale", "Yes", "Yes", "Yes"),c("Urban Settlement", "Yes", "Yes", "Yes"),c("Country FE", "Yes", "Yes", "Yes")),
          intercept.top = F,
          style = "apsr",
          table.placement = "H"
          )


```




```{r es8 old code}


# 
# 
# #germany
# m8_de_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgatnd ,
#              data = df8_de, family = "binomial")
# 
# m8_de_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    pray,
#              data = df8_de, family = "binomial")
# 
# m8_de_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgdgr,
#              data = df8_de, family = "binomial")
# 
# mr8_de_ch <- as.data.frame(summary(margins(m8_de_ch, variables = c("rlgatnd"))))
# mr8_de_pry <- as.data.frame(summary(margins(m8_de_pry, variables = c("pray"))))
# mr8_de_rlg <- as.data.frame(summary(margins(m8_de_rlg, variables = c("rlgdgr"))))
# 
# 
# #poland
# m8_pl_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgatnd ,
#              data = df8_pl, family = "binomial")
# 
# m8_pl_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    pray,
#              data = df8_pl, family = "binomial")
# 
# m8_pl_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgdgr,
#              data = df8_pl, family = "binomial")
# 
# mr8_pl_ch <- as.data.frame(summary(margins(m8_pl_ch, variables = c("rlgatnd"))))
# mr8_pl_pry <- as.data.frame(summary(margins(m8_pl_pry, variables = c("pray"))))
# mr8_pl_rlg <- as.data.frame(summary(margins(m8_pl_rlg, variables = c("rlgdgr"))))
# 
# 
# #italy
# m8_it_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgatnd ,
#              data = df8_it, family = "binomial")
# 
# m8_it_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    pray,
#              data = df8_it, family = "binomial")
# 
# m8_it_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgdgr,
#              data = df8_it, family = "binomial")
# 
# mr8_it_ch <- as.data.frame(summary(margins(m8_it_ch, variables = c("rlgatnd"))))
# mr8_it_pry <- as.data.frame(summary(margins(m8_it_pry, variables = c("pray"))))
# mr8_it_rlg <- as.data.frame(summary(margins(m8_it_rlg, variables = c("rlgdgr"))))
# 
# 
# 
# #finland
# m8_fi_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgatnd ,
#              data = df8_fi, family = "binomial")
# 
# m8_fi_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    pray,
#              data = df8_fi, family = "binomial")
# 
# m8_fi_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgdgr,
#              data = df8_fi, family = "binomial")
# 
# mr8_fi_ch <- as.data.frame(summary(margins(m8_fi_ch, variables = c("rlgatnd"))))
# mr8_fi_pry <- as.data.frame(summary(margins(m8_fi_pry, variables = c("pray"))))
# mr8_fi_rlg <- as.data.frame(summary(margins(m8_fi_rlg, variables = c("rlgdgr"))))
# 
# 
# res8 <- rbind(m8_ch_mr,m8_pry_mr,m8_rlg_mr,mr8_de_ch, mr8_de_pry, mr8_de_rlg,
#               mr8_pl_ch, mr8_pl_pry, mr8_pl_rlg, mr8_it_ch, mr8_it_pry, mr8_it_rlg,
#               mr8_fi_ch, mr8_fi_pry, mr8_fi_rlg)
# 
# res8$model <- c("all", "all","all","DE","DE","DE","PL","PL","PL",
#                "IT","IT","IT","FI","FI","FI")

```

```{r read raw data ESS8 social}

# #raw8 <- read_dta("ESS8e02_2/ESS8e02_2.dta")
# 
# #df8_raw <- raw8
# 
# df8 <- raw8[, c("idno", "cntry", "rlgdnm", "rlgblg", "lrscale", "agea", "gndr", "hinctnta", "eisced", "domicil", "rlgatnd", "rlgdgr", "pray", 'prtvtbat', 'prtvtcbe', 'prtvtdcz', 'prtvtfee', 'prtvtdfi', 'prtvtcfr', 'prtvede1', 'prtvede2', 'prtvtehu', 'prtvtbit', 'prtvtfnl', 'prtvtbno', 'prtvtdpl', 'prtvtbse', 'prtvtfch', 'prtvtbgb', 'vote', 'sclmeet')]
# 
# df8$pray <-  abs(df8$pray - 8 )
# df8$rlgatnd <-  abs(df8$rlgatnd - 8 )
# df8$urban <-  abs(df8$domicil - 6 )
# df8$female <- df8$gndr - 1
# 
# df8$ageasq <- df8$agea^2
# 
# df8 <- filter(df8, cntry %in% c('AT', 'BE', 'CZ', 'EE', 'FI', 'FR', 'DE',
#                                 'HU', 'IT', 'NL', 'NO', 'PL', 'SE', 'CH', 'GB'))
# 
# df8 <- filter(df8, vote == 1)
# 
# df8 <- filter(df8, eisced != 55)
# 
# df8$relg <- ifelse(df8$rlgdnm %in% c(1:4), 1, ifelse(df8$rlgdnm == 6, 2, 
#                                              ifelse(df8$rlgdnm %in% c(5,7,8), 3, 0)))
# 
# 
# df8 <- df8[, !(colnames(df8) %in% c("rlgdnm", "rlgblg", "gndr", "domicil", "vote"))]
# 
# df8_at  <- filter(df8, cntry == "AT", relg == 1)
# df8_be  <- filter(df8, cntry == "BE", relg == 1)
# df8_cz  <- filter(df8, cntry == "CZ", relg == 1)
# df8_ee  <- filter(df8, cntry == "EE", relg == 1)
# df8_fi  <- filter(df8, cntry == "FI", relg == 1)
# df8_fr  <- filter(df8, cntry == "FR", relg == 1)
# df8_de  <- filter(df8, cntry == "DE", relg == 1)
# df8_hu  <- filter(df8, cntry == "HU", relg == 1)
# df8_it  <- filter(df8, cntry == "IT", relg == 1)
# df8_nl  <- filter(df8, cntry == "NL", relg == 1)
# df8_no  <- filter(df8, cntry == "NO", relg == 1)
# df8_pl  <- filter(df8, cntry == "PL", relg == 1)
# df8_se  <- filter(df8, cntry == "SE", relg == 1)
# df8_ch  <- filter(df8, cntry == "CH", relg == 1)
# df8_gb  <- filter(df8, cntry == "GB", relg == 1)
# 
# 
# df8_at$pop  <- ifelse(df8_at$prtvtbat == 3, 1,  
#                ifelse(!is.na(df8_at$prtvtbat), 0, NA))
# 
# df8_be$pop  <- ifelse(df8_be$prtvtcbe == 7, 1,  
#                ifelse(!is.na(df8_be$prtvtcbe), 0, NA))
# 
# df8_cz$pop  <- ifelse(df8_cz$prtvtdcz == 7, 1,  
#                ifelse(!is.na(df8_cz$prtvtdcz), 0, NA))
# 
# df8_ee$pop  <- ifelse(df8_ee$prtvtfee == 6, 1,  
#                ifelse(!is.na(df8_ee$prtvtfee), 0, NA))
# 
# df8_fi$pop  <- ifelse(df8_fi$prtvtdfi == 4, 1,  
#                ifelse(!is.na(df8_fi$prtvtdfi), 0, NA))
# 
# df8_fr$pop  <- ifelse(df8_fr$prtvtcfr == 2, 1,  
#                ifelse(!is.na(df8_fr$prtvtcfr), 0, NA))
# 
# df8_de$pop  <- ifelse(df8_de$prtvede1 == 6, 1,  
#                ifelse(!is.na(df8_de$prtvede1), 0, NA))
# 
# df8_hu$pop  <- ifelse(df8_hu$prtvtehu %in% c(1,2), 1,  
#                ifelse(!is.na(df8_hu$prtvtehu), 0, NA))
# 
# df8_it$pop  <- ifelse(df8_it$prtvtbit %in% c(9,10), 1,  
#                ifelse(!is.na(df8_it$prtvtbit), 0, NA))
# 
# df8_nl$pop  <- ifelse(df8_nl$prtvtfnl == 3, 1,  
#                ifelse(!is.na(df8_nl$prtvtfnl), 0, NA))
# 
# df8_no$pop  <- ifelse(df8_no$prtvtbno == 8, 1,  
#                ifelse(!is.na(df8_no$prtvtbno), 0, NA))
# 
# df8_pl$pop  <- ifelse(df8_pl$prtvtdpl %in% c(2,6), 1,  
#                ifelse(!is.na(df8_pl$prtvtdpl), 0, NA))
# 
# df8_se$pop  <- ifelse(df8_se$prtvtbse == 10, 1,  
#                ifelse(!is.na(df8_se$prtvtbse), 0, NA))
# 
# df8_ch$pop  <- ifelse(df8_ch$prtvtfch == 1, 1,  
#                ifelse(!is.na(df8_ch$prtvtfch), 0, NA))
# 
# df8_gb$pop  <- ifelse(df8_gb$prtvtbgb == 7, 1,  
#                ifelse(!is.na(df8_gb$prtvtbgb), 0, NA))
# 
# 
# df8_pool <- rbind(df8_at, df8_be, df8_cz, df8_ee, df8_fi, df8_fr, df8_de, df8_hu, 
#                  df8_it, df8_nl, df8_no, df8_pl, df8_se, df8_ch, df8_gb)
# 
# df8_pool <- df8_pool[, !(colnames(df8_pool) %in% c('prtvtbat', 'prtvtcbe', 'prtvtdcz',
#                                                     'prtvtfee', 'prtvtdfi', 'prtvtcfr', 'prtvede1', 
#                                                     'prtvede2', 'prtvtehu', 'prtvtbit', 'prtvtfnl', 
#                                                     'prtvtbno', 'prtvtdpl', 'prtvtbse', 'prtvtfch', 'prtvtbgb'))]
# 
# 
# df8_pool$reg4 <- ifelse(df8_pool$cntry %in% c("AT", "BE", "FR", "DE", "NL", "CH", "GB", "IT"), "West",
#                        ifelse(df8_pool$cntry %in% c("CZ", "HU", "PL"), "East", "North"))
# 
# 
# 
# m8_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgatnd + sclmeet    + cntry,
#              data = df8_pool, family = "binomial")
# 
# m8_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + pray  + cntry,
#              data = df8_pool, family = "binomial")
# 
# m8_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + rlgdgr + cntry,
#              data = df8_pool, family = "binomial")
# 
# m8_ch_mr <- as.data.frame(summary(margins(m8_ch, variables = c("rlgatnd"))))
# m8_pry_mr <- as.data.frame(summary(margins(m8_pry, variables = c("pray"))))
# m8_rlg_mr <- as.data.frame(summary(margins(m8_rlg, variables = c("rlgdgr"))))
# 
# 
# #germany
# m8_de_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgatnd + sclmeet ,
#              data = df8_de, family = "binomial")
# 
# m8_de_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    pray,
#              data = df8_de, family = "binomial")
# 
# m8_de_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgdgr,
#              data = df8_de, family = "binomial")
# 
# mr8_de_ch <- as.data.frame(summary(margins(m8_de_ch, variables = c("rlgatnd"))))
# mr8_de_pry <- as.data.frame(summary(margins(m8_de_pry, variables = c("pray"))))
# mr8_de_rlg <- as.data.frame(summary(margins(m8_de_rlg, variables = c("rlgdgr"))))
# 
# 
# #poland
# m8_pl_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgatnd + sclmeet ,
#              data = df8_pl, family = "binomial")
# 
# m8_pl_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    pray,
#              data = df8_pl, family = "binomial")
# 
# m8_pl_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgdgr,
#              data = df8_pl, family = "binomial")
# 
# mr8_pl_ch <- as.data.frame(summary(margins(m8_pl_ch, variables = c("rlgatnd"))))
# mr8_pl_pry <- as.data.frame(summary(margins(m8_pl_pry, variables = c("pray"))))
# mr8_pl_rlg <- as.data.frame(summary(margins(m8_pl_rlg, variables = c("rlgdgr"))))
# 
# 
# #italy
# m8_it_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgatnd + sclmeet ,
#              data = df8_it, family = "binomial")
# 
# m8_it_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    pray,
#              data = df8_it, family = "binomial")
# 
# m8_it_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgdgr,
#              data = df8_it, family = "binomial")
# 
# mr8_it_ch <- as.data.frame(summary(margins(m8_it_ch, variables = c("rlgatnd"))))
# mr8_it_pry <- as.data.frame(summary(margins(m8_it_pry, variables = c("pray"))))
# mr8_it_rlg <- as.data.frame(summary(margins(m8_it_rlg, variables = c("rlgdgr"))))
# 
# 
# 
# #finland
# m8_fi_ch <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgatnd + sclmeet ,
#              data = df8_fi, family = "binomial")
# 
# m8_fi_pry <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    pray,
#              data = df8_fi, family = "binomial")
# 
# m8_fi_rlg <- glm(pop ~ lrscale + agea + ageasq + female + hinctnta + eisced + urban + 
#                    rlgdgr,
#              data = df8_fi, family = "binomial")
# 
# mr8_fi_ch <- as.data.frame(summary(margins(m8_fi_ch, variables = c("rlgatnd"))))
# mr8_fi_pry <- as.data.frame(summary(margins(m8_fi_pry, variables = c("pray"))))
# mr8_fi_rlg <- as.data.frame(summary(margins(m8_fi_rlg, variables = c("rlgdgr"))))
# 
# 
# res8_2 <- rbind(m8_ch_mr,m8_pry_mr,m8_rlg_mr,mr8_de_ch, mr8_de_pry, mr8_de_rlg,
#               mr8_pl_ch, mr8_pl_pry, mr8_pl_rlg, mr8_it_ch, mr8_it_pry, mr8_it_rlg,
#               mr8_fi_ch, mr8_fi_pry, mr8_fi_rlg)
# 
# res8_2$model <- c("all", "all","all","DE","DE","DE","PL","PL","PL",
#                "IT","IT","IT","FI","FI","FI")
# 


```

```{r CRON2W2e01}

# df_cron_raw <-  read_dta("CRON2W2e01/CRON2W2e01.dta")
# 
# df_cron <- df_cron_raw[, c("idno","cntry", "mode", "w2q69")]
# 
# df_cron$match <- paste(df_cron$idno, df_cron$cntry, df_cron$mode, sep = "-")
# 
# df_cron <- inner_join(df_cron, df10_pool, by = "match")
# 
# 
# df_cron$pray <-  abs(df_cron$pray - 8 )
# df_cron$rlgatnd <-  abs(df_cron$rlgatnd - 8 )
# df_cron$urban <-  abs(df_cron$domicil - 6 )
# df_cron$female <- df_cron$gndr - 1
# 
# df_cron$ageasq <- df_cron$agea^2
# 
# df_cron <- filter(df_cron, vote == 1)
# 
# df_cron <- filter(df_cron, eisced != 55)
# 
# df_cron$relg <- ifelse(df_cron$rlgdnm %in% c(1:4), 1, ifelse(df_cron$rlgdnm == 6, 2, 
#                                              ifelse(df_cron$rlgdnm %in% c(5,7,8), 3, 0)))
# 
# df_cron <- filter(df_cron, relg == 1)
# 
# 
# # df_cron$pop  <- ifelse(df_cron$prtvtefi == 5, 1,  
# #                ifelse(!is.na(df_cron$prtvtefi), 0, NA))
# 
# 
# df_cron$fund <- ifelse(df_cron$w2q69 %in% c(1,2,4), 0, ifelse(df_cron$w2q69 == 3, 1, NA))
# 
# df_cron <- df_cron[, c("pop", "lrscale", "agea", "ageasq" ,"female", "hinctnta", 
#                              "eisced", "urban", "rlgatnd", "pray", "rlgdgr", "fund", 'trstplt', 'psppsgva', 'psppipla')]
# 
# m_cron <- glm(pop ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd ,
#              data = df_cron, family = "binomial")
# 
# mr_cron <- as.data.frame(summary(margins(m_cron, variables = c("rlgatnd"))))
# 
# df_cor_cron <- na.omit(df_cron[, c("fund",'trstplt', 'psppsgva', 'psppipla')])
# 

```

```{r other countries}


# m10_pl <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd ,
#              data = df10[df10$cntry == "PL",], family = "binomial")
# m10_it <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd ,
#              data = df10[df10$cntry == "IT",], family = "binomial")
# m10_fi <- glm(popr ~ lrscale + agea  + ageasq + female + hinctnta + eisced + urban + rlgatnd ,
#              data = df10[df10$cntry == "FI",], family = "binomial")
# 
# mr10_de <- as.data.frame(summary(margins(m10_de, variables = c("rlgatnd"))))
# mr10_pl <- as.data.frame(summary(margins(m10_pl, variables = c("rlgatnd"))))
# mr10_it <- as.data.frame(summary(margins(m10_it, variables = c("rlgatnd"))))
# mr10_fi <- as.data.frame(summary(margins(m10_fi, variables = c("rlgatnd"))))

# res10 <- rbind(mr10_de, mr10_pl, mr10_it, mr10_fi  )



# prtvtebe
# prtvtebg
# prtvthch
# prtvtbhr
# prtvtecz
# prtvthee
# prtvtefi
# prtvtefr
# prtvtdgr
# prtvtghu
# prtvtdis
# prtvtdie
# prtvtdit
# prtvclt1
# prtvclt2
# prtvclt3
# prtvtame
# prtvthnl
# prtvtmk
# prtvtbno
# prtvtdpt
# prtvtfsi
# prtvtesk
# prtvtdgb
# prtvtcat
# prtvtccy
# prtvfde1
# prtvfde2
# prtvtalv
# prtvtepl
# prtvtars
# prtvtfes
# prtvtdse



# df10 <- filter(df10, cntry %in% c('AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 
#                                   'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU',
#                                   'IS', 'IE', 'IT', 'LT', 'LV', 
#                                   'NL', 'NO', 'PL', 'PT', 'SE', 'SK', 'SI'))

```

